name: "Setup test container"
description: "Set up test container by installing git, cloning repo and installing dependencies."
inputs:
  image:
    description: "The OS image to use in the container"
    required: true
  TZ:
    description: "Timezone"
    default: "Europe/Berlin"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup timezone
      shell: bash
      run: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    - name: 'Install dependencies (Ubuntu, Debian)'
      shell: bash
      if: ${{ contains(fromJSON('["ubuntu:focal", "ubuntu:jammy", "debian:latest"]'), inputs.image) }}
      run: |
        bash scripts/install_dependencies_debian_ubuntu.sh
        apt-get install -y curl
        curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh
        bash ./nodesource_setup.sh
        rm nodesource_setup.sh
        apt-get install -y nodejs tree
    - name: 'Install dependencies (Arch)'
      shell: bash
      if: ${{ contains('archlinux:latest', inputs.image) }}
      run: |
        bash scripts/install_dependencies_arch.sh
        pacman -Suy --noconfirm nodejs
    - name: 'Checkout repository with submodules'
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: 'Debug'
      shell: bash
      run: |
        tree
        git status
