name: "Setup test container"
description: "Set up test container by installing git, cloning repo and installing dependencies."
inputs:
  TZ:
    description: "Timezone"
    default: "Europe/Berlin"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup timezone
      shell: bash
      run: |
        ln -snf /usr/share/zoneinfo/$TZ /etc/localtime || true
        echo $TZ > /etc/timezone || true
    - name: 'Install dependencies (Ubuntu, Debian)'
      shell: bash
      if: ${{ contains(fromJSON('["ubuntu:focal", "ubuntu:jammy", "ubuntu:latest", "debian:latest"]'), env.image) }}
      run: |
        bash scripts/install_build_dependencies_debian_ubuntu.sh
    - name: 'Install dependencies (Arch)'
      shell: bash
      if: ${{ contains('archlinux:latest', env.image) }}
      run: |
        bash scripts/install_build_dependencies_arch.sh
    - name: 'Checkout repository with submodules'
      uses: actions/checkout@v3
      with:
        submodules: true
