name: Upload PPA Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-ppa:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo ${{ github.event.release.tag_name }}
