name: Upload PPA Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-ppa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: debian/latest
        fetch-depth: 0
        fetch-tags: true
    - name: Test
      run: |
        ls -la
        git status
    - name: Publish PPA
      uses: twyleg/github_action_publish_ppa_package@main
      with:
          repository: "twyleg/ppa"
          upstream_version: ${{ github.event.release.tag_name }}
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          tarball: foo
          deb_email: "mail@twyleg.de"
          deb_fullname: "Torsten Wylegala"
          series: "oracular"
