name: tests
run-name: tests
on:
  workflow_call:

  push:
    branches:
      - "**"


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: "ubuntu:latest"
    env:
      image: "ubuntu:latest"
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3
    - name: 'Setup container'
      uses: ./.github/actions/setup-build-container
    - name: 'Build'
      uses: ./.github/actions/build-project
    - name: 'Run tests'
      run: |
        cd build/tests/unit_tests/
        ./unit_tests

  smoke-test:
    runs-on: ubuntu-latest
    container:
      image: "ubuntu:latest"
    env:
      image: "ubuntu:latest"
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3
    - name: 'Setup container'
      uses: ./.github/actions/setup-build-container
    - name: 'Build'
      uses: ./.github/actions/build-project
    - name: 'Run smoke test'
      run: |
        cd build/apps/hello_world_example/
        ./hello_world_example

  build-tests-linux-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [ 'ubuntu:focal', 'ubuntu:jammy', 'debian:latest', 'archlinux:latest' ]
    env:
      image: ${{ matrix.image }}
    container:
      image: ${{ matrix.image }}
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3
    - name: 'Setup container'
      uses: ./.github/actions/setup-build-container
    - name: 'Build'
      uses: ./.github/actions/build-project
    - name: 'Upload as artifact'
      uses: ./.github/actions/upload-build-results

  build-tests-linux-use:
    needs: build-tests-linux-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [ 'ubuntu:focal', 'ubuntu:jammy', 'debian:latest', 'archlinux:latest' ]
    env:
      image: ${{ matrix.image }}
    container:
      image: ${{ matrix.image }}
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3
    - name: 'Setup container'
      uses: ./.github/actions/setup-build-container
    - name: 'Download and install build results from previous job'
      uses: ./.github/actions/download-build-results
    - name: 'Run build-test: External application - Library pulled in as system library via find_package'
      run: |
        mkdir -p tests/build_tests/test_lib_as_system_lib/build/
        cd tests/build_tests/test_lib_as_system_lib/build/
        cmake ..
        cmake --build . -- -j3
        ldd ./test_lib_as_system_lib
        ./test_lib_as_system_lib
